// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// test_wrapper
List test_wrapper(arma::mat bulkExpr, arma::mat A, arma::mat W);
RcppExport SEXP rCppGem_test_wrapper(SEXP bulkExprSEXP, SEXP ASEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type bulkExpr(bulkExprSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(test_wrapper(bulkExpr, A, W));
    return rcpp_result_gen;
END_RCPP
}
// test_draw_omega
arma::mat test_draw_omega(arma::mat omega, arma::mat psi, const arma::mat A, const arma::vec kappa, const arma::vec tau, const arma::Col<int> G);
RcppExport SEXP rCppGem_test_draw_omega(SEXP omegaSEXP, SEXP psiSEXP, SEXP ASEXP, SEXP kappaSEXP, SEXP tauSEXP, SEXP GSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const arma::Col<int> >::type G(GSEXP);
    rcpp_result_gen = Rcpp::wrap(test_draw_omega(omega, psi, A, kappa, tau, G));
    return rcpp_result_gen;
END_RCPP
}
