# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_draw_Z <- function(bulkExpr, A, W, Zik, Zjk) {
    .Call('rCppGem_test_draw_Z', PACKAGE = 'rCppGem', bulkExpr, A, W, Zik, Zjk)
}

draw_W <- function(alpha, Zjk, W) {
    .Call('rCppGem_draw_W', PACKAGE = 'rCppGem', alpha, Zjk, W)
}

test_draw_omega <- function(omega, psi, A, kappa, tau, G) {
    .Call('rCppGem_test_draw_omega', PACKAGE = 'rCppGem', omega, psi, A, kappa, tau, G)
}

test_draw_S <- function(i_zeros, A, G, S, psi, sumAS, SCrd) {
    .Call('rCppGem_test_draw_S', PACKAGE = 'rCppGem', i_zeros, A, G, S, psi, sumAS, SCrd)
}

test_draw_kappa_tau <- function(A, G, omega, p_kappa, p_tau, sumAS, kappa, tau, S) {
    .Call('rCppGem_test_draw_kappa_tau', PACKAGE = 'rCppGem', A, G, omega, p_kappa, p_tau, sumAS, kappa, tau, S)
}

