# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gem <- function(EM_CONV, MLE_CONV, EM_MAX_ITER, MLE_MAX_ITER, bulkExpr, scExpr, G, K, i_markers, alpha, p_kappa, p_tau, i_zeros, SCrd, has_BK, has_SC, M, L, N, burn_in, n_samples, thin) {
    invisible(.Call('rCppGem_gem', PACKAGE = 'rCppGem', EM_CONV, MLE_CONV, EM_MAX_ITER, MLE_MAX_ITER, bulkExpr, scExpr, G, K, i_markers, alpha, p_kappa, p_tau, i_zeros, SCrd, has_BK, has_SC, M, L, N, burn_in, n_samples, thin))
}

test_draw_Z <- function(bulkExpr, A, W, Zik, Zjk) {
    .Call('rCppGem_test_draw_Z', PACKAGE = 'rCppGem', bulkExpr, A, W, Zik, Zjk)
}

test_draw_omega <- function(omega, psi, A, kappa, tau, G) {
    .Call('rCppGem_test_draw_omega', PACKAGE = 'rCppGem', omega, psi, A, kappa, tau, G)
}

test_draw_S <- function(i_zeros, A, G, S, psi, sumAS, SCrd) {
    .Call('rCppGem_test_draw_S', PACKAGE = 'rCppGem', i_zeros, A, G, S, psi, sumAS, SCrd)
}

test_draw_kappa_tau <- function(A, G, omega, p_kappa, p_tau, sumAS, kappa, tau, S) {
    .Call('rCppGem_test_draw_kappa_tau', PACKAGE = 'rCppGem', A, G, omega, p_kappa, p_tau, sumAS, kappa, tau, S)
}

opt_MLE <- function(counts, A, exp_Zik, min_A, MLE_CONV, MLE_MAX_ITER, init_stepsize, G, SCrd, exp_Zjk, exp_logW, coeff_A, coeff_A_sq, exp_elbo_const, scExpr, exp_S, has_BK, has_SC) {
    invisible(.Call('rCppGem_opt_MLE', PACKAGE = 'rCppGem', counts, A, exp_Zik, min_A, MLE_CONV, MLE_MAX_ITER, init_stepsize, G, SCrd, exp_Zjk, exp_logW, coeff_A, coeff_A_sq, exp_elbo_const, scExpr, exp_S, has_BK, has_SC))
}

opt_Ak_full <- function(A, k, MLE_CONV, MLE_MAX_ITER, init_stepsize, min_A, gd_coeffA, gd_coeffAinv, G, coeffA, exp_S, SCrd, gd_coeffConst, u) {
    invisible(.Call('rCppGem_opt_Ak_full', PACKAGE = 'rCppGem', A, k, MLE_CONV, MLE_MAX_ITER, init_stepsize, min_A, gd_coeffA, gd_coeffAinv, G, coeffA, exp_S, SCrd, gd_coeffConst, u))
}

