# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_wrapper <- function(bulkExpr, A, W) {
    .Call('rCppGem_test_wrapper', PACKAGE = 'rCppGem', bulkExpr, A, W)
}

test_draw_omega <- function(omega, psi, A, kappa, tau, G) {
    .Call('rCppGem_test_draw_omega', PACKAGE = 'rCppGem', omega, psi, A, kappa, tau, G)
}

